name: CI-Unittest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
      # 현재 레포지토리 코드 업로드
      - uses: actions/checkout@v2

      # 정상적으로 clone 되었는지 확인
      - name: Run pwd
        run: pwd
      - name: Check directory
        run: ls -al
      
      # 필요 환경/프레임워크/언어 설치
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # 필요 패키지 설치
      - name: Install pip, pytest, flake8
        run:
          python -m pip install --upgrade pip
          pip install pytest
          pip install flake8
      
      # 코드 Lint 검증
      - name: Linting with flake8
        run:
          flake8

      # 유닛 테스트
      - name: Run my unittest
        run:
          pytest